export enum ItemUnitStatus {
  CREATED = "CREATED",
  AVAILABLE = "AVAILABLE",
  MAINTENANCE = "MAINTENANCE",
  OUT_OF_SERVICE = "OUT_OF_SERVICE",
  SOLD = "SOLD",
  RENTED = "RENTED",
  IN_TRANSIT = "IN_TRANSIT",
  RESERVED = "RESERVED",
}
