export enum RequisitionType {
    ADJUSTMENT = "ADJUSTMENT",
    PURCHASE_RECEIPT = "PURCHASE_RECEIPT",
    RENT = "RENT",
    TRANSFER = "TRANSFER",
    RETURN = "RETURN",
    CONSUMPTION = "CONSUMPTION",
    SALE = "SALE",
    INTERNAL_TRANSFER = "INTERNAL_TRANSFER"
}